import type { BubbleColor, LevelDefinition } from "@bubble-kingdom/shared";

import { createQueuePattern } from "./helpers";

interface CuratedLevelSpec {
  id: number;
  moves: number;
  palette: BubbleColor[];
  objective: LevelDefinition["objective"];
  layout: string[];
  difficulty: LevelDefinition["difficulty"];
  queuePrefix?: LevelDefinition["queue"];
  specials?: Array<{
    index: number;
    value: LevelDefinition["queue"][number];
  }>;
}

function createCuratedLevel(spec: CuratedLevelSpec): LevelDefinition {
  const chapterId = "chapter_blossom_gardens";
  const queuePrefix =
    spec.queuePrefix ??
    [
      spec.palette[0] ?? "ruby",
      spec.palette[0] ?? "ruby",
      spec.palette[1] ?? spec.palette[0] ?? "ruby",
      spec.palette[1] ?? spec.palette[0] ?? "ruby",
      spec.palette[2] ?? spec.palette[0] ?? "ruby",
      spec.palette[0] ?? "ruby",
    ];

  const queueOptions: Parameters<typeof createQueuePattern>[2] = {
    prefix: queuePrefix,
  };
  if (spec.specials) {
    queueOptions.specials = spec.specials;
  }

  return {
    id: spec.id,
    chapterId,
    indexInChapter: spec.id,
    moves: spec.moves,
    palette: spec.palette,
    objective: spec.objective,
    layout: spec.layout,
    queue: createQueuePattern(spec.palette, spec.id, queueOptions),
    rewards: {
      gold: 60 + spec.id * 5,
      petals: 6 + Math.floor(spec.id / 3),
      seasonalTokens: spec.id >= 20 ? 2 + Math.floor((spec.id - 20) / 5) : 0,
    },
    difficulty: spec.difficulty,
  };
}

export const curatedLevels: LevelDefinition[] = [
  createCuratedLevel({
    id: 1,
    moves: 16,
    palette: ["ruby", "sapphire"],
    objective: { type: "clear_all" },
    layout: [
      ". . . R R . . .",
      ". . . R R . . .",
      ". . . B B . . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 2,
    moves: 16,
    palette: ["ruby", "sapphire"],
    objective: { type: "clear_all" },
    layout: [
      ". . R B B R . .",
      ". . R R B B . .",
      ". . . R R . . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 3,
    moves: 17,
    palette: ["ruby", "sapphire", "emerald"],
    objective: { type: "clear_all" },
    layout: [
      ". . R G G R . .",
      ". . B B G G . .",
      ". . . R B . . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 4,
    moves: 17,
    palette: ["ruby", "sapphire", "emerald"],
    objective: { type: "collect_crystals", target: 2 },
    layout: [
      ". . R R B B . .",
      ". . R CR CB B . .",
      ". . B G G R . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 5,
    moves: 17,
    palette: ["ruby", "sapphire", "emerald"],
    objective: { type: "free_sprites", target: 2 },
    layout: [
      ". . G G B B . .",
      ". . G PR PG B . .",
      ". . R R G G . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 6,
    moves: 16,
    palette: ["ruby", "sapphire", "emerald"],
    objective: { type: "break_blockers", target: 2 },
    layout: [
      ". . R R B B . .",
      ". . R S IR B . .",
      ". . G G R R . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 7,
    moves: 16,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "clear_fog", target: 3 },
    layout: [
      ". . R R B B . .",
      ". . R FR FG B . .",
      ". . G FY G R . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 8,
    moves: 16,
    palette: ["ruby", "sapphire", "emerald"],
    objective: { type: "grow_flowers", target: 2 },
    layout: [
      ". . R R G G . .",
      ". . R HR HG G . .",
      ". . B B R R . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 9,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald"],
    objective: { type: "drop_artifacts", target: 1 },
    layout: [
      ". . . R R . . .",
      ". . . AR . . . .",
      ". . B B G G . .",
      ". . . . . . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 10,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "clear_all" },
    layout: [
      ". . R R B B . .",
      ". . R S IR B . .",
      ". . G G Y Y . .",
      ". . . G G . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 11,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "break_blockers", target: 3 },
    layout: [
      ". . R R B B . .",
      ". . S IR VR B . .",
      ". . G G Y Y . .",
      ". . . R G . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 12,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "collect_crystals", target: 3 },
    layout: [
      ". . R R B B . .",
      ". . R CR CB B . .",
      ". . G CG Y Y . .",
      ". . . R G . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
    specials: [{ index: 8, value: "bomb" }],
  }),
  createCuratedLevel({
    id: 13,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "free_sprites", target: 2 },
    layout: [
      ". R R B B G G .",
      ". R PR B PG G Y .",
      ". . B B Y Y . .",
      ". . . G G . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 14,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "clear_fog", target: 4 },
    layout: [
      ". . R R B B . .",
      ". . FR FG FY FB . .",
      ". . R R G G . .",
      ". . . Y Y . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "easy",
  }),
  createCuratedLevel({
    id: 15,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "drop_artifacts", target: 2 },
    layout: [
      ". . R R B B . .",
      ". . AR . . AB . .",
      ". . G G Y Y . .",
      ". . . R R . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
  }),
  createCuratedLevel({
    id: 16,
    moves: 15,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "grow_flowers", target: 3 },
    layout: [
      ". . R R G G . .",
      ". . HR HG HY G . .",
      ". . B B Y Y . .",
      ". . . R G . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
    specials: [{ index: 9, value: "line" }],
  }),
  createCuratedLevel({
    id: 17,
    moves: 14,
    palette: ["ruby", "sapphire", "emerald", "sun"],
    objective: { type: "break_blockers", target: 4 },
    layout: [
      ". R R B B G G .",
      ". S IR VR IB G Y .",
      ". . G G Y Y . .",
      ". . . R R . . .",
      ". . . . . . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
  }),
  createCuratedLevel({
    id: 18,
    moves: 14,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "clear_all" },
    layout: [
      ". R R B B G G .",
      ". R S IR VR G Y .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
    specials: [{ index: 7, value: "bomb" }],
  }),
  createCuratedLevel({
    id: 19,
    moves: 14,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "collect_crystals", target: 4 },
    layout: [
      ". R R B B G G .",
      ". R CR CB CG CY G .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
  }),
  createCuratedLevel({
    id: 20,
    moves: 14,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "free_sprites", target: 3 },
    layout: [
      ". R R B B G G .",
      ". R PR PG PY G Y .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
    specials: [{ index: 10, value: "line" }],
  }),
  createCuratedLevel({
    id: 21,
    moves: 14,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "clear_fog", target: 5 },
    layout: [
      ". R R B B G G .",
      ". FR FG FY FB FP G .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
  }),
  createCuratedLevel({
    id: 22,
    moves: 14,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "drop_artifacts", target: 2 },
    layout: [
      ". R R B B G G .",
      ". AR . AB . AG . .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
    specials: [
      { index: 8, value: "bomb" },
      { index: 12, value: "line" },
    ],
  }),
  createCuratedLevel({
    id: 23,
    moves: 13,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "grow_flowers", target: 4 },
    layout: [
      ". R R B B G G .",
      ". HR HG HY HB HP G .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
  }),
  createCuratedLevel({
    id: 24,
    moves: 13,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst"],
    objective: { type: "break_blockers", target: 5 },
    layout: [
      "R R B B G G Y Y",
      "S IR VR IB VG IY . .",
      ". B B Y Y P P .",
      ". . G G P P . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
    specials: [
      { index: 6, value: "rainbow" },
      { index: 12, value: "line" },
    ],
  }),
  createCuratedLevel({
    id: 25,
    moves: 13,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst", "aqua"],
    objective: { type: "clear_all" },
    layout: [
      "R R B B G G Y Y",
      "R C C B G G P P",
      ". B B Y Y P P .",
      ". . G G C C . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "medium",
    specials: [{ index: 8, value: "rainbow" }],
  }),
  createCuratedLevel({
    id: 26,
    moves: 13,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst", "aqua"],
    objective: { type: "collect_crystals", target: 4 },
    layout: [
      "R R B B G G Y Y",
      "CR CB CG CY P P C C",
      ". S IR VR IY P P .",
      ". . G G C C . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "hard",
    specials: [{ index: 11, value: "bomb" }],
  }),
  createCuratedLevel({
    id: 27,
    moves: 13,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst", "aqua"],
    objective: { type: "free_sprites", target: 4 },
    layout: [
      "R R B B G G Y Y",
      "PR PG PY PC P P C C",
      ". FR FG FY FC P P .",
      ". . G VG VC C . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "hard",
    specials: [{ index: 10, value: "line" }],
  }),
  createCuratedLevel({
    id: 28,
    moves: 12,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst", "aqua"],
    objective: { type: "drop_artifacts", target: 3 },
    layout: [
      "R R B B G G Y Y",
      "AR . AB . AG . AC .",
      ". B B Y Y P P .",
      ". . G G C C . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "hard",
    specials: [
      { index: 9, value: "line" },
      { index: 14, value: "bomb" },
    ],
  }),
  createCuratedLevel({
    id: 29,
    moves: 12,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst", "aqua"],
    objective: { type: "break_blockers", target: 6 },
    layout: [
      "R R B B G G Y Y",
      "S IR VR IB VG IY VC .",
      ". B B Y Y P P .",
      ". . G G C C . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "hard",
    specials: [
      { index: 6, value: "bomb" },
      { index: 11, value: "line" },
      { index: 16, value: "rainbow" },
    ],
  }),
  createCuratedLevel({
    id: 30,
    moves: 12,
    palette: ["ruby", "sapphire", "emerald", "sun", "amethyst", "aqua"],
    objective: { type: "clear_fog", target: 6 },
    layout: [
      "R R B B G G Y Y",
      "FR FG FY FB FP FC C C",
      ". B B Y Y P P .",
      ". . G G C C . .",
      ". . . R Y . . .",
      ". . . . . . . .",
    ],
    difficulty: "hard",
    specials: [
      { index: 7, value: "rainbow" },
      { index: 12, value: "line" },
    ],
  }),
];
